name: Generate and Commit File

on:
  schedule:
    # Run every Monday at 10:00 AM UTC
    - cron: "0 10 * * 1"
  push:
    branches:
      - main

jobs:
  generate-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script to generate file
        run: |
          npm install

      - name: Run script to generate file
        run: |
          # Run the parser and write to file json
          node webapp/meal-parser-node.js

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generated file"
          git push
